/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
export namespace Components {
  interface RZButton {
    class: 'is-primary' | 'is-dark' | 'is-light' | 'is-black' | 'is-text' | 'is-ghost' | 'is-link' | 'is-info' | 'is-success' | 'is-warning' | 'is-danger';
    disabled: boolean;
    shape: 'square' | 'round';
    size: 'small' | 'default' | 'large';
    type: 'button' | 'reset' | 'submit';
  }
}
declare global {
  interface HTMLRZButtonElement extends Components.RZButton, HTMLStencilElement {}
  var HTMLRZButtonElement: {
    prototype: HTMLRZButtonElement;
    new (): HTMLRZButtonElement;
  };
  interface HTMLElementTagNameMap {
    'rz-button': HTMLRZButtonElement;
  }
}
declare namespace LocalJSX {
  interface RZButton {
    class?: 'is-primary' | 'is-dark' | 'is-light' | 'is-black' | 'is-text' | 'is-ghost' | 'is-link' | 'is-info' | 'is-success' | 'is-warning' | 'is-danger';
    disabled?: boolean;
    shape?: 'square' | 'round';
    size?: 'small' | 'default' | 'large';
    type?: 'button' | 'reset' | 'submit';
  }
  interface IntrinsicElements {
    'rz-button': RZButton;
  }
}
export { LocalJSX as JSX };
declare module '@stencil/core' {
  export namespace JSX {
    interface IntrinsicElements {
      'rz-button': LocalJSX.RZButton & JSXBase.HTMLAttributes<HTMLRZButtonElement>;
    }
  }
}
